name: pokedex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.0
  json_annotation: ^4.8.0
  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.15
  http: ^1.2.2
  provider: ^6.1.2
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.5.1

flutter:
  uses-material-design: true
  assets:
    - images/fundo.jpg

